const key='tax-property-prototype-v1';
// Firebase public configuration. Access is protected by Firestore Security Rules,
// not by hiding this configuration in the browser.
const firebaseConfig={apiKey:'AIzaSyDHqzuk1uJ-cO5lQiHYabtTDH5wMJsJKF4',authDomain:'land-sign-tax-system.firebaseapp.com',projectId:'land-sign-tax-system',storageBucket:'land-sign-tax-system.firebasestorage.app',messagingSenderId:'459116004427',appId:'1:459116004427:web:7509b32a2485a45a3179ce'};
const sample={
 signs:[{id:'SG-001',name:'Food Atrium',location:'Food Atrium',width:3.4,height:4,qty:1,category:'2ก',rate:26,tax:1768,status:'ตรวจสอบแล้ว',image:'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=160&q=70'},{id:'SG-002',name:'LED Large Challenger',location:'หน้า Challenger',width:7,height:33.3,qty:1,category:'2ก',rate:52,tax:242528,status:'รอตรวจสอบ',image:'https://images.unsplash.com/photo-1519608487953-e999c86e7451?auto=format&fit=crop&w=160&q=70'}],
 land:[{deed:'12345',name:'ที่ดินโครงการ Lakefront',area:2450,use:'พาณิชยกรรม',appraisal:245000000,tax:735000,status:'ตรวจสอบแล้ว'},{deed:'67890',name:'อาคารสำนักงาน',area:840,use:'อื่น ๆ',appraisal:125000000,tax:375000,status:'ชำระแล้ว'}]};
let db=JSON.parse(localStorage.getItem(key)||'null')||sample, type='sign', editing=null, cloudDb=null, cloudReady=false;
const statusEl=()=>document.querySelector('#syncStatus');
function syncMessage(message){const el=statusEl();if(el)el.textContent=message}
function connectFirebase(){
  try{
    if(!window.firebase)throw new Error('Firebase SDK unavailable');
    if(!firebase.apps.length)firebase.initializeApp(firebaseConfig);
    cloudDb=firebase.firestore();
    const record=cloudDb.collection('taxData').doc('current');
    record.onSnapshot(async snapshot=>{
      if(snapshot.exists){
        const remote=snapshot.data();
        if(Array.isArray(remote.signs)&&Array.isArray(remote.land)){
          db={signs:remote.signs,land:remote.land}; cloudReady=true; save(); render(); syncMessage('เชื่อมข้อมูลกลางแล้ว');
        }
      }else{
        await record.set(db); cloudReady=true; syncMessage('สร้างข้อมูลกลางแล้ว');
      }
    },error=>{console.error(error);syncMessage('ใช้ข้อมูลในเครื่อง (ต้องตั้ง Firestore Rules)')});
  }catch(error){console.error(error);syncMessage('ใช้ข้อมูลในเครื่อง')}
}
const fmt=n=>'฿'+Number(n||0).toLocaleString('th-TH',{maximumFractionDigits:2});
const statusClass=s=>s==='ชำระแล้ว'?'paid':s==='ตรวจสอบแล้ว'?'checked':'pending';
function save(){
  localStorage.setItem(key,JSON.stringify(db));
  if(cloudDb&&cloudReady){
    syncMessage('กำลังบันทึกข้อมูลกลาง…');
    cloudDb.collection('taxData').doc('current').set(db).then(()=>syncMessage('เชื่อมข้อมูลกลางแล้ว')).catch(error=>{console.error(error);syncMessage('บันทึกข้อมูลกลางไม่สำเร็จ')});
  }
}
function totals(){const st=db.signs.reduce((a,x)=>a+Number(x.tax),0),lt=db.land.reduce((a,x)=>a+Number(x.tax),0),all=[...db.signs,...db.land];document.querySelector('#signTotal').textContent=fmt(st);document.querySelector('#landTotal').textContent=fmt(lt);document.querySelector('#pending').textContent=all.filter(x=>x.status==='รอตรวจสอบ').length;document.querySelector('#paid').textContent=all.length?Math.round(all.filter(x=>x.status==='ชำระแล้ว').length/all.length*100)+'%':'0%';document.querySelector('#signCompare').textContent='เทียบปีก่อน: ตั้งต้นข้อมูล';document.querySelector('#landCompare').textContent='เทียบปีก่อน: ตั้งต้นข้อมูล';document.querySelector('#recent').innerHTML=[...db.signs.map(x=>({...x,kind:'ป้าย'})),...db.land.map(x=>({...x,id:x.deed,kind:'ที่ดิน'}))].slice(0,5).map(x=>`<div class="recent-row"><span><b>${x.id}</b><br><small>${x.kind}</small></span><span>${x.name}</span><span>${fmt(x.tax)}</span><span><span class="badge ${statusClass(x.status)}">${x.status}</span></span><span>ปี 2569</span></div>`).join('')}
function render(){totals();const search=document.querySelector('#signSearch').value.toLowerCase(), status=document.querySelector('#signStatus').value;document.querySelector('#signRows').innerHTML=db.signs.filter(x=>(!search||`${x.id} ${x.name} ${x.location}`.toLowerCase().includes(search))&&(!status||x.status===status)).map(x=>`<tr><td><img class="thumb" src="${x.image}" alt="รูปป้าย"></td><td><b>${x.id}</b><br><small>${x.name}</small></td><td>${x.location}</td><td>${x.width} × ${x.height} ม. × ${x.qty}</td><td>${x.category}<br><small>${fmt(x.rate)} / 500 ตร.ซม.</small></td><td><b>${fmt(x.tax)}</b></td><td><span class="badge ${statusClass(x.status)}">${x.status}</span></td><td><button class="row-action" onclick="openEdit('sign','${x.id}')">แก้ไข</button></td></tr>`).join('');document.querySelector('#landRows').innerHTML=db.land.map(x=>`<tr><td><b>${x.deed}</b></td><td>${x.name}</td><td>${Number(x.area).toLocaleString()} ตร.ว.</td><td>${x.use}</td><td>${fmt(x.appraisal)}</td><td><b>${fmt(x.tax)}</b></td><td><span class="badge ${statusClass(x.status)}">${x.status}</span></td><td><button class="row-action" onclick="openEdit('land','${x.deed}')">แก้ไข</button></td></tr>`).join('')}
function fields(t,x={}){return t==='sign'?`<label>รหัสป้าย<input name="id" required value="${x.id||''}"></label><label>ชื่อ/รายละเอียดป้าย<input name="name" required value="${x.name||''}"></label><label>สถานที่<input name="location" required value="${x.location||''}"></label><label>หมวดภาษี<select name="category"><option ${x.category==='2ก'?'selected':''}>2ก</option><option ${x.category==='3ก'?'selected':''}>3ก</option></select></label><label>กว้าง (เมตร)<input type="number" step=".01" name="width" required value="${x.width||''}"></label><label>ยาว (เมตร)<input type="number" step=".01" name="height" required value="${x.height||''}"></label><label>จำนวนป้าย<input type="number" name="qty" required value="${x.qty||1}"></label><label>อัตราภาษี<input type="number" name="rate" required value="${x.rate||52}"></label><label>ยอดภาษี (แก้ไขได้)<input type="number" name="tax" required value="${x.tax||''}"></label><label>สถานะ<select name="status">${['รอตรวจสอบ','ตรวจสอบแล้ว','ชำระแล้ว'].map(s=>`<option ${x.status===s?'selected':''}>${s}</option>`).join('')}</select></label><label>URL รูปภาพ<input name="image" value="${x.image||''}" placeholder="วาง URL รูปภาพ"></label>`:`<label>เลขโฉนด<input name="deed" required value="${x.deed||''}"></label><label>ที่ตั้ง / โครงการ<input name="name" required value="${x.name||''}"></label><label>พื้นที่ (ตร.ว.)<input type="number" name="area" required value="${x.area||''}"></label><label>การใช้ประโยชน์<input name="use" required value="${x.use||''}"></label><label>ราคาประเมิน<input type="number" name="appraisal" required value="${x.appraisal||''}"></label><label>ภาษี<input type="number" name="tax" required value="${x.tax||''}"></label><label>สถานะ<select name="status">${['รอตรวจสอบ','ตรวจสอบแล้ว','ชำระแล้ว'].map(s=>`<option ${x.status===s?'selected':''}>${s}</option>`).join('')}</select></label>`}
function openForm(t,x=null){type=t;editing=x;document.querySelector('#modalTitle').textContent=(x?'แก้ไข':'เพิ่ม')+(t==='sign'?'รายการป้าย':'รายการที่ดิน');document.querySelector('#formFields').innerHTML=fields(t,x||{});document.querySelector('#recordModal').showModal()}
window.openEdit=(t,id)=>openForm(t,db[t==='sign'?'signs':'land'].find(x=>(t==='sign'?x.id:x.deed)===id));
document.querySelectorAll('.nav,.go-view').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===b.dataset.view));document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===b.dataset.view))});document.querySelectorAll('.go-add').forEach(b=>b.onclick=()=>openForm(b.dataset.type));document.querySelector('#signSearch').oninput=render;document.querySelector('#signStatus').onchange=render;
document.querySelector('#recordForm').onsubmit=e=>{if(e.submitter.value==='cancel')return; e.preventDefault();let x=Object.fromEntries(new FormData(e.target));['width','height','qty','rate','tax','area','appraisal'].forEach(k=>{if(k in x)x[k]=Number(x[k])});if(type==='sign'&&!x.image)x.image='https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=160&q=70';const arr=db[type==='sign'?'signs':'land'],id=type==='sign'?'id':'deed',at=editing?arr.indexOf(editing):-1;if(at>=0)arr[at]=x;else arr.push(x);save();document.querySelector('#recordModal').close();render()};
function download(t='all'){const arr=t==='sign'?db.signs:t==='land'?db.land:[...db.signs,...db.land];const csv=[Object.keys(arr[0]||{}).join(','),...arr.map(x=>Object.values(x).map(v=>`"${String(v).replaceAll('"','""')}"`).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:'text/csv'}));a.download=`tax-${t}-2569.csv`;a.click();URL.revokeObjectURL(a.href)}document.querySelector('#export').onclick=()=>download();document.querySelectorAll('.export-type').forEach(b=>b.onclick=()=>download(b.dataset.type));document.querySelector('#copyYear').onclick=()=>alert('ต้นแบบนี้เตรียม workflow คัดลอกปีไว้แล้ว — ข้อมูลกลางพร้อมใช้งาน และจะพัฒนาการแยกข้อมูลรายปีในขั้นถัดไป');render();connectFirebase();
